# Admission Controller
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
  namespace: kyverno
rules:
- verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - kyverno
  - kyverno-metrics
- verbs:
  - create
  - delete
  - get
  - patch
  - update
  apiGroups:
  - coordination.k8s.io
  resources:
  - leases
- verbs:
  - get
  - list
  - watch- patch
  - update
  apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
- verbs:
  - list
  apiGroups:
  - coordination.k8s.io
  resources:
  - leases
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
rules:
- verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
  apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiextensions.k8s.io
  - ''
  - kyverno.io
  - rbac.authorization.k8s.io
  resources:
  - customresourcedefinitions
  - configmaps
  - clusterpolicies
  - policies
  - updaterequests
  - clusterrolebindings
  - rolebindings
  - namespaces
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:admission-controller-2
  labels:
    app.kubernetes.io/component: admission-controller-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:admission-controller-2
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
  namespace: kyverno
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'kyverno:admission-controller-2'
---
# Cleanup Controller
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:cleanup-controller-2'
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      - deletecollection
    apiGroups:
      - kyverno.io
    resources:
      - clustercleanuppolicies
      - cleanuppolicies
      - clustercleanuppolicies/*
      - cleanuppolicies/*
  - verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events
  - verbs:
      - create
    apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:cleanup-controller-2
  labels:
    app.kubernetes.io/component: cleanup-controller-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:cleanup-controller-2
subjects:
  - kind: ServiceAccount
    name: kyverno-cleanup-controller
    namespace: kyverno
