kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
  namespace: kyverno
rules:
- verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  apiGroups:
  - ''
  resources:
  - secrets
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - kyverno
  - kyverno-metrics
- verbs:
  - create
  - delete
  - get
  - patch
  - update
  apiGroups:
  - coordination.k8s.io
  resources:
  - leases
- verbs:
  - get
  - list
  - watch- patch
  - update
  apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - apiextensions.k8s.io
  - ''
  - kyverno.io
  resources:
  - customresourcedefinitions
  - configmaps
  - clusterpolicies
  - policies
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno:admission-controller-2
  labels:
    app.kubernetes.io/component: admission-controller-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:admission-controller-2
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'kyverno:admission-controller-2'
  namespace: kyverno
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'kyverno:admission-controller-2'