apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-deployment-app-label
  annotations:
    policies.kyverno.io/title: Add Default App Label
    policies.kyverno.io/category: Best Practices, Other
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: >-
      Ensure deployments have a default app label if not specified.
      This policy performs a simple mutation which adds a template label
      and selector match label `app=object.name` to Deployments.      
spec:
  rules:
  - name: add-labels
    match:
      all:
      - resources:
          kinds:
          - Deployment
          namespaces:
          - "user-*"
    mutate:
      patchStrategicMerge:
        spec:
          # selector:
          #   matchLabels:
          #     +(app): "{{ `{{request.object.metadata.name}}`}}"
          template:
            metadata:
              labels:
                +(app): "{{ `{{request.object.metadata.name}}`}}"