apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-project-quota
  annotations:
    policies.kyverno.io/title: Add Quota
    policies.kyverno.io/category: Multi-Tenancy, RTC Best Practices
    policies.kyverno.io/subject: ResourceQuota, LimitRange
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      To better control the number of resources that can be created in a given
      Project and provide default resource consumption limits for Pods,
      ResourceQuota and LimitRange resources are recommended.
      This policy will generate ResourceQuota and LimitRange resources when
      a new Project is created.      
spec:
  background: false
  rules:
  - name: generate-resource-quota
    match:
      all:
      - resources:
          names:
          - "user-*"
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: ResourceQuota
      name: default-resource-quota
      synchronize: true
      namespace: "{{ `{{request.object.metadata.name}}` }}"
      data:
        spec:
          hard:
            requests.cpu: '4'
            requests.memory: '16Gi'
            limits.cpu: '4'
            limits.memory: '16Gi'
  - name: generate-limit-range
    match:
      all:
      - resources:
          kinds:
          - Namespace
          names:
          - "user-*"
    generate:
      apiVersion: v1
      kind: LimitRange
      name: default-limit-range
      synchronize: true
      namespace: "{{ `{{request.object.metadata.name}}` }}"
      data:
        spec:
          limits:
          - default:
              cpu: 500m
              memory: 1Gi
            defaultRequest:
              cpu: 200m
              memory: 256Mi
            type: Container