apiVersion: v1
data:
  clientSecret: '{{ fromSecret "openshift-config" "nyu-sso-openid-client-secret" "clientSecret" }}'
kind: Secret
metadata:
  name: nyu-sso-openid-client-secret
  namespace: rtc-policies
type: Opaque
---
apiVersion: v1
data:
  clientSecret: '{{ fromSecret "openshift-config" "hpc-sso-openid-client-secret" "clientSecret" }}'
kind: Secret
metadata:
  name: hpc-sso-openid-client-secret
  namespace: rtc-policies
type: Opaque